---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: example
data:
  REACT_APP_GLPI_URL: https://homolog-suporte.sebrae.com.br/
  REACT_APP_TOKEN_USER_GLPI: lAoKQVIi0n6TCiSka2yvRfHbTLreHUMGq0MoHnd3
  REACT_APP_TOKEN_APP_GLPI: A8ddFb7i1g4nAbWvSdS7BXr1ihDuht1YSkzn5AZ1

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-web
  labels:
    name: example-web
  namespace: example
spec:
  selector:
    matchLabels:
      name: example-web
  template:
    metadata:
      labels:
        name: example-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-map
            optional: false
        image: docker-hosted.sebrae.com.br/example-web:${TAG}
        imagePullPolicy: IfNotPresent
        name: example-web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: docker-hosted
      restartPolicy: Always